aws:
  region: eu-central-1
  key: test
  secret: test
  sqs:
    max-msg-size: 1   # 256 KB
    queue-url: http://sqs.eu-central-1.localhost.localstack.cloud:4566/000000000000/my-queue
  s3:
    bucket: my-messages-bucket